version: "3"
services:
  dashboard:
    container_name: guardrails_test_dashboard
    image: hyperdebugger/guardrails_dashboard:latest
    restart: always
    build: .
    ports: 
      - "3000:3000"
    links:
    - api
  api:
    container_name: guardrails_test_api
    image: hyperdebugger/guardrails_api:latest
    restart: always
    build: .
    ports: 
      - "9000:9000"